version: "3.9"

services:
  pseudo_rest_api:
    container_name: pseudo_rest_api_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5678:5678"
      - "24678:24678"
    volumes:
      - .:/app
      - .:/pseudo-rest-api
    command: ["npm", "run", "dev"]

