name: eslint-prettier

on: [push]

jobs:
  build:

    uses: ./.github/workflows/build.yml

  lint:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: ESLint and Prettier
        run: npm run lint

