name: eslint-prettier

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest
    name: lint
    needs: [build]

    steps:
      - name: Setup
        uses: ./.github/workflows/build.yml
      - name: ESLint and Prettier
        run: npm run lint

