name: eslint-prettier

on: [push]

jobs:
  build:

    uses: ./.github/workflows/build.yml

  lint:

    runs-on: ubuntu-latest
    name: lint
    needs: [build]

    steps:
      - name: ESLint and Prettier
        run: npm run lint

