name: eslint-prettier

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - names: Setup
        uses: ./.github/workflows/build.yml
      - name: ESLint and Prettier
        run: npm run lint

